### ISSUE TITLE
weird version name in README

### ISSUE THREAD

**Issue by cedricvanrompay** [XPIR-team/XPIR#18]
file [`README.md`](https://github.com/XPIR-team/XPIR/blob/a9391c967daf4257ef303408cbe18c00a97fc5c0/README.md) says _"v0.2.0-beta is released"_ while the latest release (in https://github.com/XPIR-team/XPIR/releases) is named `v0.1.1-beta`. That's confusing.

**Comment by carlosaguilarmelchor** [comment]
Thanks for your message @cedricvanrompay. I am waiting to merge a smal PR and I will publish the release.

**Comment by carlosaguilarmelchor** [comment]
Dear Cedric,
the release is out. I therefore close this issue. 

Thank you again for making us notice this !

best,

Carlos

**Comment by carlosaguilarmelchor** [comment]
@cedricvanrompay don't forget to star the project if you like it :)

**Comment by cedricvanrompay** [comment]
lol, true I forgot. There you go :-)

**Comment by carlosaguilarmelchor** [comment]
:) thx
