### ISSUE TITLE
Troubleshooting - error running simple pir_server, pir_client 

### ISSUE THREAD

**Issue by JoaoAndreSa** [XPIR-team/XPIR#20]
Hi,

Sorry to bother you but I was trying to run you XPIR framework but whenever I try to execute the simple client/server application I get this error...

**PIROptimizer: Error when writing optimization data, aborting.**

Do you know why does this happen? 

Best regards,
Joao Sa

**Comment by carlosaguilarmelchor** [comment]
Hi @JoaoAndreSa ,
thank you for your feedback.

Which version of XPIR are you working on ? Release v0.2.0 ? 

Normally the make procedure creates a directory exp under the client and server directories.

You are getting this error because this directory does not exist. To solve it quickly just do "mkdir exp" at the client's and server's directories.

Please can you give us how did you get and install xpir ? (to allow us to track why this directory was not created)

best,

Carlos

**Comment by JoaoAndreSa** [comment]
Unfortunately, this did not solve the problem (the directory exp was already there!) :\

I am working on release v0.2.0. (git clone https://github.com/XPIR-team/XPIR.git) and installed XPIR on Ubuntu 14.04 - 3.13.0-85-generic, using normal compiling commands (cmake, make, make check, ...).

Here is the full execution of the server:

**PIRServer: Launching DBDirectoryProcessor without file splitting
DBDirectoryProcessor: 16 entries processed
DBDirectoryProcessor: The size of the database is 16777216 bytes
DBDirectoryProcessor: The number of elements in the catalog is 16
PIRServer: Creating new PIRSession
sendCatalog : done.
PIRSession: Notifying the client this is a client-driven session
OptimService: Could not access cache file
PIROptimizer: Absorption and precompute performance cache is outdated, regenerating it
PIROptimizer: Generating cache for Paillier:100 :2048:4096
PIRReplyGeneratorGMP: Global reply generation took 0.359584 seconds
PIRReplyGeneratorGMP: Global reply generation took 0.714042 seconds
PIROptimizer: Generating cache for Paillier:128:3072:6144
PIRReplyGeneratorGMP: Global reply generation took 1.025495 seconds
PIROptimizer: Generating cache for Paillier:192:7680:15360
PIRReplyGeneratorGMP: Global reply generation took 10.840788 seconds
PIROptimizer: Generating cache for Paillier:80:1024:2048
PIRReplyGeneratorGMP: Global reply generation took 0.053624 seconds
PIRReplyGeneratorGMP: Global reply generation took 0.106933 seconds
PIRReplyGeneratorGMP: Global reply generation took 0.229002 seconds
PIRReplyGeneratorGMP: Global reply generation took 0.454551 seconds
PIRReplyGeneratorGMP: Global reply generation took 0.903802 seconds
PIROptimizer: Error when writing optimization data, aborting.**

**Comment by carlosaguilarmelchor** [comment]
Ok I got it. You type sudo make instead of make. Therefore the exp directory belongs to root and you cannot write on it. :)

```
sudo rm -rf _build 
mkdir _build
cd _build
cmake ..
make 
```

or 

```
cd _build
chown -R $USER:$USER *
```

Should do it !

**Comment by carlosaguilarmelchor** [comment]
@JoaoAndreSa, any success with the solution above ?

**Comment by JoaoAndreSa** [comment]
Yes, it worked! Thank you very much @carlosaguilarmelchor

**Comment by carlosaguilarmelchor** [comment]
Great ! Don't forget to star the project if you like it ! :)
