### ISSUE TITLE
Problem with the print inside the library

### ISSUE THREAD

**Issue by AlbertoArdu** [XPIR-team/XPIR#26]
For our project we make use of the standard output to communicate with a python script. I think is better to avoid prints inside the library if DEBUG is not defined.
In the file PIRReplyExtraction_internal.cpp in function extractReply() there are printouts.

**Comment by carlosaguilarmelchor** [comment]
Hi,
thank you for your feedback. Can you test the fix above ? (branch feature/remove-verbosity-in-api)

Best,

Carlos
PS : If you like our project don't forget to star it :)

**Comment by AlbertoArdu** [comment]
Hello!
Working perfectly well. 
Thank you
