### ISSUE TITLE
Catalog object

### ISSUE THREAD

**Issue by JoaoAndreSa** [XPIR-team/XPIR#27]
Hi,

I was wondering if you could help me with something. I was adapting the apps/server and apps/client to work with my solution (pipeline version) but I am kind of stuck in the the client's startProcessResult() function. 

In your case you use data from this 'catalog' object both for the reply extractor and reply writer. **How can I do the same thing without this 'catalog' ?** (client knows which element to query so no need for this catalog step).

Thanks,
Joao Sa

**Comment by JoaoAndreSa** [comment]
I think I solved the issue by changing the PIRReplyWriter class (simply removed the 'catalog' objet and sent the necessary parameters  - maxFileSize, chosen element, etc.)

**Comment by carlosaguilarmelchor** [comment]
Cool :) I therefore close the issue.
