### ISSUE TITLE
unused functions

### ISSUE THREAD

**Issue by nicolasAmat** [XPIR-team/XPIR#28]
Several functions are actually unused.

Functions :
'DEBUG_MESSAGE' in /XPIR-master/crypto/NFLlib.cpp
'allocandcomputeShouppoly' in /XPIR-master/crypto/NFLlib.hpp
'allocpoly' in /XPIR-master/crypto/NFLlib.cpp
'bitsplitter_backtoback_internal_test' in /XPIR-master/crypto/NFLlib.cpp
'blo' in XPIR-master/apps/server/PIRSession.cpp
'file_exists' in /XPIR-master/apps/client/DESC.cpp
'generateReplyExternal' in /XPIR-master/pir/replyGenerator/PIRReplyGeneratorNFL_internal.cpp
'getAllOptimData' in /XPIR-master/pir/optim/OptimService.cpp
'getChosenElement' in /XPIR-master/pir/queryGen/PIRQueryGenerator_internal.cpp
'getChosenFileSize' in /XPIR-master/pir/replyExtraction/PIRReplyExtraction_internal.cpp
'getCiphertextBytesize' in /XPIR-master/crypto/HomomorphicCrypto.hpp
'getCiphertextSize' in /XPIR-master/crypto/NFLLWEPublicParameters.cpp
'getOneCryptoSystem' in /XPIR-master/crypto/HomomorphicCryptoFactory_internal.cpp
'getParameters' in /XPIR-master/apps/optim/PIROptimizer.cpp
'getbits' in /XPIR-master/crypto/PaillierKeys.cpp
'getsecretKey' in /XPIR-master/crypto/NFLLWE.cpp
'gotoLine' in /XPIR-master/pir/optim/OptimService.cpp
'isFinished' in /XPIR-master/apps/server/PIRSession.cpp
'mulandaddPolyNTTShoup' in /XPIR-master/crypto/NFLlib.hpp
'mulmodPolyNTT' in /XPIR-master/crypto/NFLlib.hpp
'mulmodPolyNTTShoup' in /XPIR-master/crypto/NFLlib.hpp
'setPIRParameters' in /XPIR-master/pir/queryGen/PIRQueryGenerator_internal.cpp
'setType' in /XPIR-master/pir/optim/OptimVars.cpp
'setWrittenSize' in /XPIR-master/pir/events/WriteEvent.cpp
'sighandler' in /XPIR-master/apps/client/main.cpp
'submodPoly' in /XPIR-master/crypto/NFLlib.hpp 
'verifyOptimData' in /XPIR-master/pir/optim/OptimService.cpp
'writeLWEFile' in /XPIR-master/pir/optim/OptimService.cpp
'writeOptimData' in /XPIR-master/pir/optim/OptimService.cpp

**Comment by carlosaguilarmelchor** [comment]
Thx Nicolas. 
DEBUG_MESSAGE and bitsplitter_backtoback_internal_test are there for debugging purposes so it is normal that they are not used.

For the other fucntions can you try to remove them and do a PR after testing it is ok ???
thx :)

Carlos

**Comment by nicolasAmat** [comment]
Sorry for these two functions ^^
Perfect for me.
Thx ! 
Nicolas

**Comment by carlosaguilarmelchor** [comment]
Solved by #30
