### ISSUE TITLE
Unread and Unused Variables

### ISSUE THREAD

**Issue by nicolasAmat** [XPIR-team/XPIR#32]
Several variables are actually unused or unread in the code.

Variables with the actual location : 
- 'read_size' in /XPIR/apps/optimPIROptimizer.cpp line 1015
- 'nbFiles' in /XPIR/apps/server/PIRSession.cpp line 48
- 'start' in /XPIR/apps/server/PIRSession.cpp line 387
- 'i' in /XPIR/apps/server/PIRSession.cpp line 516
- 'wasVerbose' in /XPIR/apps/server/PIRSession.cpp line 438
- 'maxFileBytesize' in /XPIR/apps/simplepir/simplePIR.cpp line 303
- 'A_bits' in /XPIR/crypto/NFLLWE.cpp line 289
- 'k_str' in /XPIR/crypto/NFLLWE.cp line 568
- 'isnt_unit32PerChunk' in /XPIR/crypto/NFLIB.cpp line 455
- 'subchunkMasks' in /XPIR/crypto/NFLlib.cpp line 470
- 'isint_unit64PerChunk' in /XPIR/crypto/NFLlib.cpp line 682
- 'i' in /XPIR/crypto/PaillierAdapter.cpp line 299
- 'i' in /XPIR/pir/libpir.cpp line 29
- 'current_bytesskipped' in /XPIR/PIR/replyExtraction/PIRReplyWritter.cpp line 125
- 'abs_size' in /XPIR/pir/replyGenerator/PIRReplyGeneratorGMP.cpp line 126
- raw_data' in /XPIR/pir/replyGenerator/PIRReplyGeneratorGMP.cpp line 127
- 'affichages in /XPIR/pir/replyGenerator/PIRReplyGeneratorGMP.cpp line 304
- 'now' in /XPIR/pir/replyGenerator/PIRReplyGeneratorNFL_internal.cpp line 98
- 'delta' in /XPIR/pir/replyGenerator/PIRReplyGeneratorNFL_internal.cpp line 98
-' nflptr' in /XPIR/pir/replyGenerator/PIRReplyGeneratorNFL_internal.cpp line 476
- 'jumpcipher' in /XPIR/pir/replyGenerator/PIRReplyGeneratorNFL_internal.cpp line 170
- 'usable_memory' in /XPIR/pir/replyGenerator/PIRReplyGeneratorNFL_internal.cpp line 216
- 'max_memory_per_file' in /XPIR/pir/replyGenerator/PIRReplyGeneratorNFL_internal.cpp line 206
- 'database_size' in /XPIR/pir/replyGenerator/PIRReplyGeneratorNFL_internal.cpp line 310

Maybe I forgot some variables...

Others trival imporvments will be find.

**Comment by nicolasAmat** [comment]
Some variables are initialized by getters, so I won't removed theses. And I won't touch to NFLIB.
I do the PR tomorrow.

Nicolas

**Comment by carlosaguilarmelchor** [comment]
PR merged :)
