### ISSUE TITLE
problem with LWE

### ISSUE THREAD

**Issue by thierno30** [XPIR-team/XPIR#41]
i am using this library , but when the choice algorithm for the PIR is LWE , the protocol run and it display succes, when i go inside reception folder i find another file not that i have chosen

**Comment by carlosaguilarmelchor** [comment]
Hi @thierno30 sorry for the long delay we missed your issue. Can you provide us a complete reproducible example?

Carlos

**Comment by carlosaguilarmelchor** [comment]
Closed due to a lack of reproducibility
