### ISSUE TITLE
Peformance Comparison

### ISSUE THREAD

**Issue by ReverseControl** [XPIR-team/XPIR#42]
Hello,

Curious, has there been any work done in comparing the XPIR implementation and https://github.com/ReverseControl/MuchPIR, or other similar PIR implementations?

Thanks.

**Comment by carlosaguilarmelchor** [comment]
You can look in google scholar for papers who cited the XPIR paper. Here is what you'll find : 
https://scholar.google.fr/scholar?cites=10897862530512700279&as_sdt=2005&sciodt=0,5&hl=fr

Among these papers you will find some papers that use XPIR, and many others which propose PIR protocols and compare XPIR with a variety of alternative PIR protocols.

best,
Carlos

**Comment by carlosaguilarmelchor** [comment]
Oh by the way, MuchPIR looks great! Congrats for that work!!!
