### ISSUE TITLE
Wrong database during simplepir?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [XPIR-team/XPIR#43]
Today I have a look at simplepir.cc and I find test case 9 use database that prepared for test case 8:
https://github.com/XPIR-team/XPIR/blob/9bfc1cc56afaba63c20cdf843183304df60c4d3e/apps/simplepir/simplePIR.cpp#L344
this maybe a carelessness, but don't import any error because choose index is 0.

**Comment by carlosaguilarmelchor** [comment]
Thank you for your issue! Solved in the commit noted above. Closing issue.
